version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: Crucibleai-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./backend/.env:/app/.env          # Mount .env into container
    env_file:
      - ./backend/.env                    # Also load envs into process
    working_dir: /app

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: crucibleai-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
