[package]
name = "ServerTemplate"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
dotenv = "0.15.0"
reqwest = {version = "0.12.20", features = ["json"]}
serde = {version = "1.0.219" , features = ["derive"]}
serde_json = "1.0.140"
tokio = {version = "1.45.1" , features = ["full"]}
async-trait = "0.1.88"
actix-cors = "0.7.1"
log = "0.4.27"